name: RUNPYYYYYYYYYYYYYYY


on:
 workflow_dispatch:


jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Set Up Python 3.10
         uses: actions/setup-python@v3
         with:
              python-version: "3.10"

       - name: Updating PIP
         run: python -m pip install --upgrade pip

       - name: Installing Requirements Module
         run: python -m pip install -r requirements.txt

       - name: Running Python File
         run: python bot.py
